### ISSUE TITLE
How is this test passing? It's ignoring the collection filter

### ISSUE THREAD

**Issue by dahmc** [firebase/quickstart-testing#110]
Nothing is changed in the code below, all taken from the repo as-is:

This is one of the tests that is defined:
```javascript
  it("tests a Cloud Firestore function", async () => {
    const wrapped = test.wrap(myFunctions.firestoreUppercase);

    // Make a fake document snapshot to pass to the function
    const after = test.firestore.makeDocumentSnapshot(
      {
        text: "hello world",
      },
      "/collection/foo"
    );

    // Call the function
    await wrapped(after);

    // Check the data in the Firestore emulator
    const snap = await admin.firestore().doc("/uppercase/foo").get();
    expect(snap.data()).to.eql({
      text: "HELLO WORLD",
    });
  }).timeout(5000);

```

And this is the corresponding cloud function
```javascript
/**
 * Firestore-triggered function which uppercases a string field of a document.
 */
exports.firestoreUppercase = functions.firestore
  .document("/lowercase/{doc}")
  .onCreate(async (doc, ctx) => {
    const docId = doc.id;

    const docData = doc.data();
    const lowercase = docData.text;

    const firestore = admin.firestore();
    await firestore.collection("uppercase").doc(docId).set({
      text: lowercase.toUpperCase(),
    });
  });
```

Now, this functions works exactly how it's supposed to, when testing manually in the emulator.
- If I create a document under `/lowercase` collection, it make an uppercase one.
- If I create a document under `/foobar` collection, it doesn't do anything.

That's expected, since the listener of the cloud function is 
```javascript
functions.firestore.document("/lowercase/{doc}")
```
So it only listens to the `/lowercase` collection.

However... I don't get how the test is passing.
The test adds a document under the collection `/collection`
```javascript
// Make a fake document snapshot to pass to the function
    const after = test.firestore.makeDocumentSnapshot(
      {
        text: "hello world",
      },
      "/collection/foo"
    );
```

Since the cloud function only listens to `/lowercase`, how is this passing?

And it doesn't matter what I pass in here as a collection in the test, it always passes. How?

**Comment by samtstern** [comment]
@dahmc thanks for pointing this out. When you use the `firebase-functions-test` library you're directly invoking the function (`await wrapped(after)`) so you're bypassing the check for a matching trigger.  As you can see in the body of the function only the `id` part of the path is used which is `foo` in both `/lowercase/foo` and `/collection/foo`.

In production a write to `/collection/foo` would *not* trigger that function.

**Comment by dahmc** [comment]
@samtstern Thanks for pointing that out.

Is this not documented somewhere? I couldn't find it.

Also, what I'm doing now to even test the trigger is using `@firebase/rules-unit-testing` instead. I'm writing an actual doc, and then wait for the function to do its thing. Seems to be more of a complete test for me, or am I getting that wrong?

**Comment by samtstern** [comment]
@dahmc yes that's more complete! For RTDB or Firestore triggers that can be easier, it depends if the function has observable side-effects or not.

The behavior you asked about is not documented anywhere explicitly, we believe it is implied since you're literally invoking the function directly so there's no way it won't run. But thanks for pointing out the mistake in the tests!

**Comment by dahmc** [comment]
Thanks for the clarification!
