### ISSUE TITLE
[Question] How to setup a user that has their email verified

### ISSUE THREAD

**Issue by VictorUvarov** [firebase/quickstart-testing#19]
Since a helper function for `firestore.rules` would look like 
```js
function emailVerified() {
  return request.auth.token.email_verified;
}
```
I assumed the setup with this quickstart would look like this
```js
const bob = getAuthedFirestore({
  uid: "bob",
  token: { email_verified: true },
});
```
Any guidance would help very much.

**Comment by samtstern** [comment]
@ViktorUvarov I recently submitted a change to `@firebase/rules-unit-testing` to make this a lot easier:
https://github.com/firebase/firebase-js-sdk/pull/3876

Once the next release comes out (they usually happen weekly) you can do something like this:

```js
const firebase = require('@firebase/rules-unit-testing`);

const app = firebase.initializeTestApp({
  projectId: 'foo',
  auth: {
    uid: "bob",
    email: "bob@example.com",
    email_verified: true
  }
);
```
