### ISSUE TITLE
I am looking for a better stack to do unit-tests with Firestore

### ISSUE THREAD

**Issue by regnou** [firebase/quickstart-testing#247]
Please, I enjoy firebase, but I don t enjoy non-modern web developement using Typescript and a more recent Test Runner, I mean at least Jest or Vitest...
I have encountered issues with firebase SDK 9 and unit testing.
I have 2 questions there:
simple one:
https://stackoverflow.com/questions/72580518/do-you-have-a-simple-project-example-that-run-some-unit-tests-with-firestore-sdk
detailed one:
https://stackoverflow.com/questions/72539977/error-on-having-vitest-and-firestore-working-inside-a-sveltekit-project

I have done many tests with your project, and I am not sure about that, but I think Firebase SDK 9 has some errors when doing the same tests you offer in this quickstart (firestore+sdk9+unit-testing), but using 'imports' instead of 'require' makes some issues. TO REPRODUCE THE ERROR, launch tests for this file, but replace REQUIRE with IMPORTS.
https://github.com/firebase/quickstart-testing/blob/master/unit-test-security-rules-v9/test/firestore.spec.js

So then I decide to use mocha instead of Vitest, to not use SecurityRulesTesting (because it does not works with imports), and then I realize than I am using also Typescript, and I have to do more configurations on mocha for that ... etc... it never ends.

I am asking to this community, if they know a project (demo, starter...) with a modern stack to do some UNIT TESTS with FIRESTORE. Please, I am looking for this stack: FIRESTORE SDK 9 + VITEST (or if really it does not work with vitest, maybe Jest is a good alternative) + IMPORTS (aka ES6 module) + TYPESCRIPT. Do you know some sample anywhere to do Firestore Unit Testing with this stack ?

**Comment by ithinco** [comment]
Me too

**Comment by regnou** [comment]
hello, can you delete this issue please ?
