### ISSUE TITLE
Example of how to test auth triggers

### ISSUE THREAD

**Issue by hernantz** [firebase/quickstart-testing#49]
Hi, now that we have the auth emulator, it would be nice to have an example test that showcases how to work with the auth emulator on the test suit.
I've been trying to get this to work, without success.

```js
const firebase = require('@firebase/testing');

// Project id passed by emulators:exec.
const PROJECT_ID = process.env.GCLOUD_PROJECT;
const CREDS = { uid: TEST_USER_ID };

// To get a logged in user pass the CREDS object as param, or null for unauthenticated requests.
const getDB = (creds) => firebase.initializeTestApp({ projectId: PROJECT_ID, auth: creds }).firestore();

// Admin tool to bypass rules and generate data in the db.
const admin = firebase.initializeAdminApp({ projectId: PROJECT_ID });
const getAdminDB = () => admin.firestore();
const getAuth = () => admin.auth();

describe("The cloud functions backend", () => {

    describe("when a user is created", () => {

        it("populates some fields for that user document", async () => {
            const admin = getAdminDB();
            const auth = getAuth();
            const phone = "+11234567891";
            const photo = "https://foo.bar";

            const user = await auth.createUser({ phoneNumber: phone, photoURL: photo, uid: "123" });
            const userRef = admin.collection("users").doc("123");

            await new Promise((resolve) => {
                unsubscribe = userRef.onSnapshot(snap => {
                    const { phoneNumber, photoURL } = snap.data();
                    expect(phoneNumber).to.eq(phone);
                    expect(photoURL).to.eq(photo);
                    unsubscribe();
                    resolve();
                });
            });
        });

    });

});
```

The error is:
```
Your API key is invalid, please check you have copied it correctly.
```
Could it be that the `FIREBASE_AUTH_EMULATOR_HOST` is not being set by `firebase emulators:exec`? and need to be specified explicitly? Like: `auth().useEmulator("localhost:9099")`?

Appreciate some ideas on how to troubleshoot or some code snippets that use the auth emulator in tests. Thanks!

**Comment by samtstern** [comment]
@hernantz the first thing you'll want to do is upgrade from `@firebase/testing`, which we deprecated recently, to `@firebase/rules-unit-testing` which is totally backwards compatible but has some nice improvements as well. One of the main improvements is that `initializeAdminApp()` actually relies on the real `firebase-admin` library not a fake implementation.  The reason that's important is because `firebase-admin` is the library that knows how to interpret `FIREBASE_AUTH_EMULATOR_HOST`.  

It's possible that this upgrade alone will resolve your bug.

After you do that make sure that you're also using the latest version of the Firebase CLI so that we can be sure `emulators:exec` is setting `FIREBASE_AUTH_EMULATOR_HOST`.

**Comment by hernantz** [comment]
Hey @samtstern, appreciate your response!
I've updated to latest versions: 

```
  "dependencies": {
    "firebase-tools": "^8.15.1"
  },
  "devDependencies": {
    "@firebase/rules-unit-testing": "^1.1.0",
    "firebase-admin": "^9.3.0",
    "mocha": "^8.2.1"
  },
  "scripts": {
    "start": "npx firebase emulators:start --import . --export-on-exit",
    "test": "npx firebase emulators:exec --project emulator-test 'mocha --timeout 5000 --exit'",
    "deploy": "npx firebase deploy"
  },
```
There you can also see the test script I'm running.

That has changed the error to be:
```
     Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal. Error code: ENOTFOUND".
```
And the `FIREBASE_AUTH_EMULATOR_HOST` is still not set. Could there be another thing I'm missing here?

```js
const firebase = require("@firebase/rules-unit-testing");

// Project id and emulator host passed by emulators:exec.
const PROJECT_ID = process.env.GCLOUD_PROJECT;

// Admin tool to bypass rules and generate data in the db.
const admin = firebase.initializeAdminApp({ projectId: PROJECT_ID });
const adminDB = admin.firestore();
const adminAuth = admin.auth();


describe("The cloud functions backend", () => {

    describe("when a user is created", () => {

        it("populates some fields for that user document", async () => {
            const phone = "+11234567891";
            const photo = "https://foo.bar";

            const user = await adminAuth.createUser({ phoneNumber: phone, photoURL: photo, uid: "123" });
            const userRef = adminDB.collection("users").doc("123");

            await new Promise((resolve) => {
                unsubscribe = userRef.onSnapshot(snap => {
                    const { phoneNumber, photoURL } = snap.data();
                    expect(phoneNumber).to.eq(phone);
                    expect(photoURL).to.eq(photo);
                    unsubscribe();
                    resolve();
                });
            });
        });

    });

});
```

Thanks again!

**Comment by samtstern** [comment]
@hernantz I feel like you're exactly one step ahead of me!  You're running into two bugs that I am working on today:

1. `FIREBASE_AUTH_EMULATOR_HOST` missing in `emulators:exec` - https://github.com/firebase/firebase-tools/pull/2800
2. `firebase-admin` requires credentials for auth operations even when talking to the emulator - https://github.com/firebase/firebase-admin-node/pull/1085

The good news is they should be fairly simple to workaround until I fix them:

1. Set the env var yourself
2. Run `gcloud auth application-default login` on your development machine

**Comment by hernantz** [comment]
haha this is such a relief, I knew something fishy was going on. I'll keep an eye on these tickets, and once again, thanks for the quick response!

**Comment by hernantz** [comment]
@samtstern thanks for pushing this forward, I've updated to the latest versions and my test now works! Appreciate your efforts!

**Comment by samtstern** [comment]
@hernantz thanks for following up!  Glad to hear this was solved.  I'll add an auth example to this repo now.
