### ISSUE TITLE
Readme need to update for run the test at unit-test-cloud-functions

### ISSUE THREAD

**Issue by rubiagatra** [firebase/quickstart-testing#57]
I try to run the test by using readme on https://github.com/firebase/quickstart-testing/tree/master/unit-test-cloud-functions. It returns an error.

I am using ubuntu 20.04

```
firebase emulators:exec --project=fakeproject' npm run test'

error: missing required argument 'script'
```

need to update to

```
firebase emulators:exec --project=fakeproject 'npm run test'
```

**Comment by samtstern** [comment]
Fixed by #58
