### ISSUE TITLE
Simple http function throws ensure "done()" is called instead of actual assertion error.

### ISSUE THREAD

**Issue by zgosalvez** [firebase/quickstart-testing#82]
Change the following assertion so that it fails:
https://github.com/firebase/quickstart-testing/blob/9e2ca9c469116b2e297bf5862e654c5aa576de45/unit-test-cloud-functions/functions/test/functions.spec.js#L30
It will throw the following error:
```log
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. ([redacted]/functions/lib/test/index.test.js)
```
This makes it very difficult to debug issues. Instead, I recommend (unless there's a better way to debug this):
```ts
try {
  expect(text).to.eq("text: input");
} catch (e) {
  console.error(e);
  throw e;
}
```

**Comment by samtstern** [comment]
@zgosalvez thanks for pointing this out!  You're right this is not a great example, I will take a look.
